### PR TITLE
Contacts Test Updates

### PR DESCRIPTION
**Pull request by tiny-dancer**
piggy backs off open spec perf pull request: https://github.com/expo/test-suite/pull/3

> currently assumes each query able field is defined at least once across all contacts on test device   

https://github.com/expo/test-suite/pull/3
image

is related to an android contacts module rewrite pr

### CODE REVIEW

**Comment by tiny-dancer** [comment]
@aalices, 

> however we have no guarantee if the field actually exists cause a contact might not have a field set.

hmm, sorry not sure i'm following? is it related to my comment "currently assumes each query able field is defined at least once for any contact across all contacts on test device"?

when adding create and remove functionality i planned to appropriately set up and tear down seeded contacts for testing reliability.

> Can you make sure you only modify Contacts tests? 

this was added in https://github.com/expo/test-suite/pull/3 and is meant to be added seperately

> Adding time measurement is not actually needed here as we only check if the method work as expected.

time measurement is common in unit test frameworks and often used as another assertion step for performance, especially functional tests such as these that don't run on mocks.  in this case it helped to quickly assert performance improvement while remaining functional status quo.  additionally the data of the time measurements could be expanded on to show trending performance over time, etc.

and it's fun to see :)

if not desired will remove accordingly.
 

thanks for the review!

**Comment by tiny-dancer** [comment]
1. awesome, didn't notice the stubs prior - is it android only?
2. ten four.

**Comment by esamelson** [comment]
hi - yes, the tests are currently Android only, though I expect we'll use similarly stubbed contacts when we have iOS automated tests as well.

also note that if you do go the route of changing the stubbed test contacts, they'll need to be backwards compatible (e.g. current tests must all still pass) since we run test-suite for all supported SDK versions.

thanks so much!

**Comment by ide** [comment]
We are moving test-suite to the main Expo repo here (https://github.com/expo/expo/tree/master/apps/test-suite) and are archiving this repo. This makes it simpler to contribute API changes, which may require unit tests, integration tests, and new docs along with the API change. Please send PRs and issues to the main Expo repo. Thank you.

**Pull request closed without merging**
